# UltraScan III Documentation Configuration
#
# Sphinx configuration file for building the UltraScan documentation.
# See the Sphinx documentation for the full list of configuration options:
# https://www.sphinx-doc.org/

# ---------------------------------------------------------------------------
# Path setup
#
# If Python modules need to be imported for autodoc, add them to sys.path
# here.
#
# Example:
#   import os
#   import sys
#   sys.path.insert(0, os.path.abspath('../src'))
# ---------------------------------------------------------------------------

import datetime
import re
from pathlib import Path
from sphinxcontrib.qthelp import QtHelpBuilder


# ---------------------------------------------------------------------------
# Fix: sphinxcontrib-qthelp hardcodes "doc" as the virtualFolder in .qhp/.qhcp.
# Subclass the builder to rewrite it to "manual" after generation.
# ---------------------------------------------------------------------------
class UltraScanQtHelpBuilder(QtHelpBuilder):
    name = 'qthelp'

    def build_qhp(self, outdir, outname):
        super().build_qhp(outdir, outname)
        for suffix in ('.qhp', '.qhcp'):
            f = Path(outdir) / f'{outname}{suffix}'
            if f.exists():
                f.write_text(
                    re.sub(r'\bdoc\b', 'manual', f.read_text(encoding='utf-8'), count=2),
                    encoding='utf-8'
                )


def setup(app):
    app.add_builder(UltraScanQtHelpBuilder, override=True)

# -- Project information -----------------------------------------------------

project = 'UltraScan III'
author = (
    "Emre Brookes, Borries Demeler, Bruce Dubbs, "
    "Haben Gabir, Gary Gorbet, Saeed Mortezazadeh, "
    "Alexey Savelyev, and Dan Zollars"
)

copyright = f"{datetime.datetime.now().year}, AUC Solutions LLC"

# The short X.Y version
version = '4.1'
# The full version, including alpha/beta/rc tags
release = '4.1.0'


# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.graphviz',
    'sphinx.ext.autosectionlabel',
    'sphinx_design',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'haiku'

html_title = f"{project} Documentation v{release}"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Custom static assets (CSS, images)
html_static_path = ['_static']
html_extra_path = ['images']

html_css_files = [
    'custom.css',
]

# ---------------------------------------------------------------------------
# QtHelp / Qt Assistant configuration
#
# These settings control the help files used by Qt Assistant:
#
#   manual.qhp   (Qt help project)
#   manual.qhcp  (Qt help collection project)
#   manual.qch   (compiled help file)
#   manual.qhc   (help collection database)
#
# The UltraScan GUI launches Assistant with:
#
#   Assistant -collectionFile <bin>/manual.qhc
#
# The QHC and QCH files must reside in the same directory at runtime.
# ---------------------------------------------------------------------------

# Namespace used by Qt Assistant URLs
qthelp_namespace = "ultrascaniii"

# Base filename for generated help files
qthelp_basename = "manual"

# HTML help builder (Windows CHM)
htmlhelp_basename = "UltraScanIII"

# Prevent Sphinx from generating empty <filterAttribute> tags in QtHelp files.
qthelp_filters = []

# ---------------------------------------------------------------------------
# LaTeX output
#
# This configuration enables generation of a printable PDF manual via:
#
#     sphinx-build -b latex
#
# The LaTeX output is not used by the UltraScan GUI help system (which
# uses QtHelp via Qt Assistant), but it allows developers or users to
# generate a standalone PDF version of the documentation.
# ---------------------------------------------------------------------------

# Use XeLaTeX for proper Unicode support
latex_engine = "xelatex"

latex_elements = {
    # Paper size for the generated PDF
    'papersize': 'letterpaper',

    # Font size
    'pointsize': '11pt',

    # Improve figure placement for technical documentation
    'figure_align': 'htbp',

    # LaTeX preamble additions
    'preamble': r"""
\usepackage{graphicx}
""",
}

# Group the document tree into a LaTeX document
#
# (source start file, output tex file, title, author, documentclass)
#
latex_documents = [
    (
        master_doc,
        'UltraScanIII.tex',
        f'UltraScan III Manual',
        author,
        'manual',
    ),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'ultrascaniii', 'UltraScan III Manual',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'UltraScanIII', 'UltraScan III Manual',
     author, 'UltraScanIII',
     'Comprehensive data analysis software for hydrodynamic data from analytical ultracentrifugation experiments.',
     'Science'),
]
