######################################################################
# Automatically generated by qmake (3.1) Sat Nov 21 12:08:04 2020
######################################################################

TEMPLATE = app
TARGET = shmutil

# Input
SOURCES += main.cpp
