#!/bin/csh
#SBATCH -A TG-MCB070039N
#SBATCH -J htry10run1       # job name
#SBATCH -o job.out         # output and error file name (%j expands to jobID)
#SBATCH -n 1024          # total number of mpi tasks requested
#SBATCH -p normal          # queue (partition) -- normal, development, etc.
#SBATCH -t 02:00:00           # run time (hh:mm:ss)
#SBATCH --mail-user=emre.brookes@umt.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

cd /scratch/00451/tg457210/testx
module load python
ibrun pmijobrun.sh
