#ifndef PIXMAPS_H
#define PIXMAPS_H

static const char *print_xpm[] = { "32 32 12 1",
                                   "a c #ffffff",
                                   "h c #ffff00",
                                   "c c #ffffff",
                                   "f c #dcdcdc",
                                   "b c #c0c0c0",
                                   "j c #a0a0a4",
                                   "e c #808080",
                                   "g c #808000",
                                   "d c #585858",
                                   "i c #00ff00",
                                   "# c #000000",
                                   ". c None",
                                   "................................",
                                   "................................",
                                   "...........###..................",
                                   "..........#abb###...............",
                                   ".........#aabbbbb###............",
                                   ".........#ddaaabbbbb###.........",
                                   "........#ddddddaaabbbbb###......",
                                   ".......#deffddddddaaabbbbb###...",
                                   "......#deaaabbbddddddaaabbbbb###",
                                   ".....#deaaaaaaabbbddddddaaabbbb#",
                                   "....#deaaabbbaaaa#ddedddfggaaad#",
                                   "...#deaaaaaaaaaa#ddeeeeafgggfdd#",
                                   "..#deaaabbbaaaa#ddeeeeabbbbgfdd#",
                                   ".#deeefaaaaaaa#ddeeeeabbhhbbadd#",
                                   "#aabbbeeefaaa#ddeeeeabbbbbbaddd#",
                                   "#bbaaabbbeee#ddeeeeabbiibbadddd#",
                                   "#bbbbbaaabbbeeeeeeabbbbbbaddddd#",
                                   "#bjbbbbbbaaabbbbeabbbbbbadddddd#",
                                   "#bjjjjbbbbbbaaaeabbbbbbaddddddd#",
                                   "#bjaaajjjbbbbbbaaabbbbadddddddd#",
                                   "#bbbbbaaajjjbbbbbbaaaaddddddddd#",
                                   "#bjbbbbbbaaajjjbbbbbbddddddddd#.",
                                   "#bjjjjbbbbbbaaajjjbbbdddddddd#..",
                                   "#bjaaajjjbbbbbbjaajjbddddddd#...",
                                   "#bbbbbaaajjjbbbjbbaabdddddd#....",
                                   "###bbbbbbaaajjjjbbbbbddddd#.....",
                                   "...###bbbbbbaaajbbbbbdddd#......",
                                   "......###bbbbbbjbbbbbddd#.......",
                                   ".........###bbbbbbbbbdd#........",
                                   "............###bbbbbbd#.........",
                                   "...............###bbb#..........",
                                   "..................###..........." };


static const char *zoom_xpm[] = { "32 32 8 1",
                                  "# c #000000",
                                  "b c #c0c0c0",
                                  "a c #ffffff",
                                  "e c #585858",
                                  "d c #a0a0a4",
                                  "c c #0000ff",
                                  "f c #00ffff",
                                  ". c None",
                                  "..######################........",
                                  ".#a#baaaaaaaaaaaaaaaaaa#........",
                                  "#aa#baaaaaaaaaaaaaccaca#........",
                                  "####baaaaaaaaaaaaaaaaca####.....",
                                  "#bbbbaaaaaaaaaaaacccaaa#da#.....",
                                  "#aaaaaaaaaaaaaaaacccaca#da#.....",
                                  "#aaaaaaaaaaaaaaaaaccaca#da#.....",
                                  "#aaaaaaaaaabe###ebaaaaa#da#.....",
                                  "#aaaaaaaaa#########aaaa#da#.....",
                                  "#aaaaaaaa###dbbbb###aaa#da#.....",
                                  "#aaaaaaa###aaaaffb###aa#da#.....",
                                  "#aaaaaab##aaccaaafb##ba#da#.....",
                                  "#aaaaaae#daaccaccaad#ea#da#.....",
                                  "#aaaaaa##aaaaaaccaab##a#da#.....",
                                  "#aaaaaa##aacccaaaaab##a#da#.....",
                                  "#aaaaaa##aaccccaccab##a#da#.....",
                                  "#aaaaaae#daccccaccad#ea#da#.....",
                                  "#aaaaaab##aacccaaaa##da#da#.....",
                                  "#aaccacd###aaaaaaa###da#da#.....",
                                  "#aaaaacad###daaad#####a#da#.....",
                                  "#acccaaaad##########da##da#.....",
                                  "#acccacaaadde###edd#eda#da#.....",
                                  "#aaccacaaaabdddddbdd#eda#a#.....",
                                  "#aaaaaaaaaaaaaaaaaadd#eda##.....",
                                  "#aaaaaaaaaaaaaaaaaaadd#eda#.....",
                                  "#aaaaaaaccacaaaaaaaaadd#eda#....",
                                  "#aaaaaaaaaacaaaaaaaaaad##eda#...",
                                  "#aaaaaacccaaaaaaaaaaaaa#d#eda#..",
                                  "########################dd#eda#.",
                                  "...#dddddddddddddddddddddd##eda#",
                                  "...#aaaaaaaaaaaaaaaaaaaaaa#.####",
                                  "...########################..##." };


/* XPM */
static const char *configure_32_xpm[] = { "32 32 358 2",
                                          "  	c None",
                                          ". 	c #9A9899",
                                          "+ 	c #7D7A7B",
                                          "@ 	c #B6B5B5",
                                          "# 	c #C3C1C2",
                                          "$ 	c #C7C6C6",
                                          "% 	c #C4C4C5",
                                          "& 	c #F4F3F4",
                                          "* 	c #F9F9F9",
                                          "= 	c #A09E9F",
                                          "- 	c #C0BFBF",
                                          "; 	c #DEDCDD",
                                          "> 	c #E2E2E2",
                                          ", 	c #EAEAEA",
                                          "' 	c #DFDEDE",
                                          ") 	c #A5A3A3",
                                          "! 	c #999797",
                                          "~ 	c #FFFFFF",
                                          "{ 	c #EBEBEB",
                                          "] 	c #8C8A8B",
                                          "^ 	c #C8C7C7",
                                          "/ 	c #C6C5C7",
                                          "( 	c #C4C3C3",
                                          "_ 	c #D4D3D3",
                                          ": 	c #979596",
                                          "< 	c #686666",
                                          "[ 	c #C1C1C1",
                                          "} 	c #F5F5F4",
                                          "| 	c #ECEBEB",
                                          "1 	c #8F8D8E",
                                          "2 	c #A3A2A2",
                                          "3 	c #F0F0F0",
                                          "4 	c #B4B3B3",
                                          "5 	c #BCBBBB",
                                          "6 	c #C6C5C5",
                                          "7 	c #4D4A4B",
                                          "8 	c #6D6A6B",
                                          "9 	c #9F9D9E",
                                          "0 	c #EDEDED",
                                          "a 	c #D8D5D6",
                                          "b 	c #949293",
                                          "c 	c #F5F5F5",
                                          "d 	c #FEFFFF",
                                          "e 	c #D0CFCF",
                                          "f 	c #BFBDBE",
                                          "g 	c #5B5857",
                                          "h 	c #787576",
                                          "i 	c #ACAAAA",
                                          "j 	c #8A8888",
                                          "k 	c #3E383A",
                                          "l 	c #D1CFCF",
                                          "m 	c #D1CECF",
                                          "n 	c #939091",
                                          "o 	c #6A6768",
                                          "p 	c #FEFEFE",
                                          "q 	c #F4F4F4",
                                          "r 	c #C7C7C6",
                                          "s 	c #C3C3C2",
                                          "t 	c #8B8989",
                                          "u 	c #959394",
                                          "v 	c #D1D0D0",
                                          "w 	c #C2C0C1",
                                          "x 	c #7E7B7B",
                                          "y 	c #423A3C",
                                          "z 	c #CFCECF",
                                          "A 	c #D0CDCE",
                                          "B 	c #949192",
                                          "C 	c #797776",
                                          "D 	c #FCFDFC",
                                          "E 	c #DEDEDE",
                                          "F 	c #D5D5D5",
                                          "G 	c #9B9999",
                                          "H 	c #898787",
                                          "I 	c #C9C8C8",
                                          "J 	c #3F383A",
                                          "K 	c #CFCDCE",
                                          "L 	c #D5D2D3",
                                          "M 	c #858181",
                                          "N 	c #E0DEDF",
                                          "O 	c #8C8A8A",
                                          "P 	c #757373",
                                          "Q 	c #DDDDDC",
                                          "R 	c #878686",
                                          "S 	c #676465",
                                          "T 	c #3E3436",
                                          "U 	c #C6C4C4",
                                          "V 	c #D6D4D3",
                                          "W 	c #949292",
                                          "X 	c #9D9B9B",
                                          "Y 	c #D5D3D3",
                                          "Z 	c #A4A1A1",
                                          "` 	c #534F4F",
                                          " .	c #666363",
                                          "..	c #ACA9A9",
                                          "+.	c #F0EFEE",
                                          "@.	c #CDCCCD",
                                          "#.	c #686566",
                                          "$.	c #C1BDBD",
                                          "%.	c #D7D4D3",
                                          "&.	c #938D9C",
                                          "*.	c #C8C7C8",
                                          "=.	c #BEBDBD",
                                          "-.	c #858383",
                                          ";.	c #585556",
                                          ">.	c #C5C3C4",
                                          ",.	c #EEEEEE",
                                          "'.	c #E3E3E3",
                                          ").	c #7C7A7A",
                                          "!.	c #CAC7C6",
                                          "~.	c #D4D1D1",
                                          "{.	c #929090",
                                          "].	c #0D50BA",
                                          "^.	c #5A7AB3",
                                          "/.	c #B5AFB7",
                                          "(.	c #A5A4B5",
                                          "_.	c #A19F9F",
                                          ":.	c #D5D5D6",
                                          "<.	c #E4E3E4",
                                          "[.	c #A29FA0",
                                          "}.	c #A3A2A3",
                                          "|.	c #C9C9CB",
                                          "1.	c #D1CDCD",
                                          "2.	c #D0CCCB",
                                          "3.	c #928F8F",
                                          "4.	c #0844B2",
                                          "5.	c #003FBF",
                                          "6.	c #1261D7",
                                          "7.	c #426CB6",
                                          "8.	c #B0ACB7",
                                          "9.	c #8F8D90",
                                          "0.	c #595759",
                                          "a.	c #D2CDCB",
                                          "b.	c #D7D0CA",
                                          "c.	c #835982",
                                          "d.	c #E14943",
                                          "e.	c #69242B",
                                          "f.	c #187BF5",
                                          "g.	c #0454D5",
                                          "h.	c #233B77",
                                          "i.	c #B9BBCA",
                                          "j.	c #F6C5C0",
                                          "k.	c #ED908C",
                                          "l.	c #BF1B1B",
                                          "m.	c #C51D1D",
                                          "n.	c #B7565A",
                                          "o.	c #003FCE",
                                          "p.	c #B54657",
                                          "q.	c #FCF7F2",
                                          "r.	c #EB7D7C",
                                          "s.	c #A91919",
                                          "t.	c #B51B1B",
                                          "u.	c #E03F3C",
                                          "v.	c #99517A",
                                          "w.	c #E76F72",
                                          "x.	c #C82727",
                                          "y.	c #EA7676",
                                          "z.	c #EE9393",
                                          "A.	c #EB7C7C",
                                          "B.	c #BA1D1E",
                                          "C.	c #277DD7",
                                          "D.	c #75111C",
                                          "E.	c #B2181A",
                                          "F.	c #A31818",
                                          "G.	c #D03635",
                                          "H.	c #FAE6E6",
                                          "I.	c #EC8888",
                                          "J.	c #B41D1D",
                                          "K.	c #9E1717",
                                          "L.	c #4D91D8",
                                          "M.	c #033BA4",
                                          "N.	c #01289F",
                                          "O.	c #700A0E",
                                          "P.	c #B0181A",
                                          "Q.	c #E55A58",
                                          "R.	c #B82020",
                                          "S.	c #E45353",
                                          "T.	c #EC8686",
                                          "U.	c #BF2828",
                                          "V.	c #9D1717",
                                          "W.	c #6BA4DD",
                                          "X.	c #0D45A9",
                                          "Y.	c #002296",
                                          "Z.	c #0253D0",
                                          "`.	c #388CEB",
                                          " +	c #8F568A",
                                          ".+	c #9F1717",
                                          "++	c #AD1818",
                                          "@+	c #9C1717",
                                          "#+	c #F2AEAE",
                                          "$+	c #CD3434",
                                          "%+	c #931616",
                                          "&+	c #76A9DE",
                                          "*+	c #1951AF",
                                          "=+	c #001C8C",
                                          "-+	c #014AC7",
                                          ";+	c #297FE4",
                                          ">+	c #479AF0",
                                          ",+	c #0165DA",
                                          "'+	c #AA1919",
                                          ")+	c #AB1919",
                                          "!+	c #EF9898",
                                          "~+	c #F4BABA",
                                          "{+	c #C82E2E",
                                          "]+	c #961616",
                                          "^+	c #8E1515",
                                          "/+	c #981616",
                                          "(+	c #609AD8",
                                          "_+	c #1F57B3",
                                          ":+	c #001885",
                                          "<+	c #0143BF",
                                          "[+	c #1C72DD",
                                          "}+	c #4F9EF0",
                                          "|+	c #1061CB",
                                          "1+	c #A41818",
                                          "2+	c #B01A1A",
                                          "3+	c #F1A5A5",
                                          "4+	c #F5C2C2",
                                          "5+	c #971616",
                                          "6+	c #8F1515",
                                          "7+	c #4481CA",
                                          "8+	c #235EB9",
                                          "9+	c #00137B",
                                          "0+	c #003AB4",
                                          "a+	c #1060D2",
                                          "b+	c #509DEF",
                                          "c+	c #2174D8",
                                          "d+	c #0544A9",
                                          "e+	c #B61E1E",
                                          "f+	c #F6C8C8",
                                          "g+	c #F4BBBB",
                                          "h+	c #C22626",
                                          "i+	c #8B1414",
                                          "j+	c #951616",
                                          "k+	c #306FBE",
                                          "l+	c #2364C2",
                                          "m+	c #001A84",
                                          "n+	c #0034AE",
                                          "o+	c #0B55CA",
                                          "p+	c #4793E9",
                                          "q+	c #3181E0",
                                          "r+	c #084AAE",
                                          "s+	c #9B1717",
                                          "t+	c #BD2323",
                                          "u+	c #F7D2D2",
                                          "v+	c #C72C2C",
                                          "w+	c #2A67B8",
                                          "x+	c #2B73CE",
                                          "y+	c #001E89",
                                          "z+	c #0030AB",
                                          "A+	c #0850C7",
                                          "B+	c #3C87E3",
                                          "C+	c #3F8AE3",
                                          "D+	c #0B4BB2",
                                          "E+	c #A01717",
                                          "F+	c #AF1C1C",
                                          "G+	c #BF2323",
                                          "H+	c #F9DCDC",
                                          "I+	c #F8D4D4",
                                          "J+	c #C82D2D",
                                          "K+	c #8D1515",
                                          "L+	c #A81B1A",
                                          "M+	c #225DB1",
                                          "N+	c #2E77D4",
                                          "O+	c #002692",
                                          "P+	c #002BA6",
                                          "Q+	c #074DC5",
                                          "R+	c #317FE0",
                                          "S+	c #478FE8",
                                          "T+	c #0E50B8",
                                          "U+	c #871414",
                                          "V+	c #BC2525",
                                          "W+	c #F5C5C5",
                                          "X+	c #F6CCCC",
                                          "Y+	c #941616",
                                          "Z+	c #921515",
                                          "`+	c #B92B23",
                                          " @	c #1B56B0",
                                          ".@	c #3E88E2",
                                          "+@	c #2E75D6",
                                          "@@	c #0D47B8",
                                          "#@	c #0346C1",
                                          "$@	c #2C79DF",
                                          "%@	c #4D97EB",
                                          "&@	c #1256C0",
                                          "*@	c #C22929",
                                          "=@	c #B31C1C",
                                          "-@	c #F3B6B6",
                                          ";@	c #F6C7C7",
                                          ">@	c #CB2E2E",
                                          ",@	c #2E77D7",
                                          "'@	c #1B63D3",
                                          ")@	c #1960D0",
                                          "!@	c #438AE4",
                                          "~@	c #3680E2",
                                          "{@	c #4791EA",
                                          "]@	c #145BC7",
                                          "^@	c #073A9B",
                                          "/@	c #9A1717",
                                          "(@	c #C22828",
                                          "_@	c #B51D1D",
                                          ":@	c #C92F2F",
                                          "<@	c #B92425",
                                          "[@	c #1B55B3",
                                          "}@	c #165ED1",
                                          "|@	c #277BE5",
                                          "1@	c #3D86E5",
                                          "2@	c #1761CF",
                                          "3@	c #063CA5",
                                          "4@	c #C12424",
                                          "5@	c #B71F1F",
                                          "6@	c #F3B2B2",
                                          "7@	c #D03434",
                                          "8@	c #E04949",
                                          "9@	c #11429D",
                                          "0@	c #1357CA",
                                          "a@	c #1E7DEE",
                                          "b@	c #82E4FE",
                                          "c@	c #4BA2F4",
                                          "d@	c #145FD6",
                                          "e@	c #022E8D",
                                          "f@	c #861414",
                                          "g@	c #B81B1B",
                                          "h@	c #F2ADAD",
                                          "i@	c #FDF9F9",
                                          "j@	c #E34747",
                                          "k@	c #113D97",
                                          "l@	c #2574E0",
                                          "m@	c #4699F2",
                                          "n@	c #2169D6",
                                          "o@	c #072773",
                                          "p@	c #4F0808",
                                          "q@	c #AE1A1A",
                                          "r@	c #B91C1C",
                                          "s@	c #EA7A7A",
                                          "t@	c #E45050",
                                          "u@	c #0A1C51",
                                          "v@	c #082063",
                                          "w@	c #0A1536",
                                          "x@	c #120C0A",
                                          "y@	c #1D1610",
                                          "z@	c #1D1812",
                                          "A@	c #1D1915",
                                          "B@	c #1D1916",
                                          "C@	c #1E1B18",
                                          "D@	c #1E1C1A",
                                          "E@	c #1E1D1B",
                                          "F@	c #1D1D1C",
                                          "G@	c #1C1E1D",
                                          "H@	c #1B1E1E",
                                          "I@	c #1A1E1F",
                                          "J@	c #181E1F",
                                          "K@	c #161E1F",
                                          "L@	c #151F1F",
                                          "M@	c #131D1E",
                                          "N@	c #111C1D",
                                          "O@	c #0D1B1D",
                                          "P@	c #300405",
                                          "Q@	c #6A0C0C",
                                          "  . +                                         @ # $ %           ",
                                          "  & * =                                   - ; > , ' )           ",
                                          "  ! ~ { ]                               ^ / ( _ : <             ",
                                          "    [ } | 1                           2 3 4 5 6 7       8       ",
                                          "      9 0 a b                         c d e f : g   h i j       ",
                                          "        k l m n                     o p ~ q r s t u v w x       ",
                                          "          y z A B                   C ~ ~ D E F G H I n         ",
                                          "            J K L b                 M ~ N O P Q _ R I S         ",
                                          "              T U V W               X Y Z `  ...+.@.#.          ",
                                          "                  $.%.B             &.*.=.-.;.>.,.'.).          ",
                                          "                    !.~.{.        ].^./.(._.:.<.[.}.|.          ",
                                          "                      1.2.3.    4.5.6.7.8.9.0.                  ",
                                          "                        a.b.  c.d.e.f.g.h.                      ",
                                          "                          i.j.k.l.m.n.o.                        ",
                                          "                          p.q.r.s.t.u.                          ",
                                          "                        v.w.x.y.z.A.B.                          ",
                                          "                      C.D.E.F.G.H.I.J.K.                        ",
                                          "                    L.M.N.O.P.Q.R.S.T.U.F.V.                    ",
                                          "                  W.X.Y.Z.`. +.+++@+y.#+$+@+%+                  ",
                                          "                &+*+=+-+;+>+,+    '+)+!+~+{+]+^+/+              ",
                                          "              (+_+:+<+[+}+|+      K.1+2+3+4+{+5+6+6+            ",
                                          "            7+8+9+0+a+b+c+d+        5+5+e+f+g+h+5+i+j+          ",
                                          "          k+l+m+n+o+p+q+r+            .+s+t+u+~+v+j+i+K.        ",
                                          "        w+x+y+z+A+B+C+D+              E+F+]+G+H+I+J+j+K+L+      ",
                                          "      M+N+O+P+Q+R+S+T+                  U+V+]+G+W+X+J+Y+Z+`+    ",
                                          "     @.@+@@@#@$@%@&@                      Y+*@/+=@-@;@>@Y+V.    ",
                                          "    ,@'@)@!@~@{@]@^@                        /@(@s+_@#+4+:@%+<@  ",
                                          "  [@}@    |@1@2@3@                            .+4@1+5@3+6@7@8@  ",
                                          "  9@0@a@b@c@d@e@                                f@g@1+t.h@i@j@  ",
                                          "    k@l@m@n@o@                                    p@q@r@s@t@    ",
                                          "      u@v@w@  x@y@z@A@B@C@D@E@F@G@H@I@J@K@L@M@N@O@  P@@+Q@      ",
                                          "                                                                " };


/* XPM */
static const char *vec_xpm[] = { "32 32 5 1",
                                 "  c #C0C0C0",
                                 ". c #FFFFFF",
                                 "X c #FFFF00",
                                 "o c #0000FF",
                                 "O c None",
                                 "oooooooooooooooooooooooooooooooo",
                                 "ooooooooooooooooooooooooooooXooo",
                                 "oooooooo ooooooooooooXooooooXoXX",
                                 "oooooooooooooooooooooXXXoooXXoXo",
                                 "oooooooooooooooooooooXXXXooXXXoo",
                                 "oooooooo oooooooooooXoXXXXXXoXoo",
                                 "ooooooooooooooooXooXXoXXoXoooXoo",
                                 "oo.oo.oo.oo.ooXoXXoXXooXoo.oo.oo",
                                 "oooooooo oooooXXXoXXoooooooooooo",
                                 "ooooooooooXoooXXooXooooooooooooX",
                                 "ooooooooooXoooXXoooooooooooooXoX",
                                 "oooooooo oXoooXXoooooooooooooXXX",
                                 "oooooooooXoXXXXooooooooooooXoXXo",
                                 "oooooXoooXoXoXXooooooooooXoXXoXo",
                                 "oooooXXoXXoooooooooooooooXoXXooo",
                                 "ooooXXXXXooooooooooooooooXXXoooo",
                                 "ooooXXXXoooooooooooooooooXXXoooo",
                                 "ooooXXXo oooooooooooooooXooXoooo",
                                 "ooooXXooooooooooooooooooXooooooo",
                                 "ooooXXooooooooooooooXooXoooooooo",
                                 "oooXoooo oooooooooooXXXooooooooo",
                                 "oooXooooooooooooooooXoXooooooooo",
                                 "ooXoooooooooooooooXoXooooooooooo",
                                 "ooXooooo oooooooooXXXooooooooooo",
                                 "oXooooooooooooooooXXoooooooooooo",
                                 "oXooooooooooooooXoXooooooooooooo",
                                 "oXoooooo oooooooXXoooooooooooooo",
                                 "XooooooooooooooXoooooooooooooooo",
                                 "XooooooooooooooXoooooooooooooooo",
                                 "Xooooooo oooooXooooooooooooooooo",
                                 "ooooooooooooooXoooooooooooooooXo",
                                 "oooooooooooooXooooooooooooooooXX" };


/* XPM */
static const char *ras_xpm[] = { "32 32 6 1",
                                 "  c #000000",
                                 ". c #FF0000",
                                 "X c #FFFFFF",
                                 "o c #BDBDBD",
                                 "O c #00FF00",
                                 "+ c None",
                                 "O O   O  O   O  O O O     O O OO",
                                 "OO     O      OO OOOOO  O    OO ",
                                 "   OO   OOOO  O OO OOOOOO    OX ",
                                 "O O OO   O   O OOO O O OOOOOOOOO",
                                 "OOO  OO OO O  OO O  OOO OO OO OO",
                                 "OOOO O   O O O  OO OO OOOOOOO O ",
                                 " OOO O  OO  OO O     OOOOOOO  O ",
                                 " OOO   OOOOOO OOOOO   OOOO O OOO",
                                 "OOOOOOO  OOOO   OOOO  O  OOOOOO ",
                                 " OO  OOOO  O OO OOOO OO OO OOOOO",
                                 "O OOO OOOO  OOO OOO  OOOOOOOOOO ",
                                 "O OOOOOO OOOOOO OOOOOOO  OOO  OO",
                                 "O OOOOOOOOOOOOOOOOOOOOOOOO   OO ",
                                 "OOOOO  OOOOO OOOOOOOOOOOOOOO O O",
                                 "OOOOOOO OOOOOO  OOOOOOOOOOOOO XO",
                                 "OOOOOOOOOOOOOO OOOOO OO O OOOOOO",
                                 "OO.OOOOO.OOOOOOOOOOO.OOO.OOOOOOO",
                                 "OOOOOOOOOOOOOOOOO.OOOOOOOO.OOOOO",
                                 "OOOOOOOO  OOOOO OO OOOOOOOO OOOO",
                                 " OOOOOOOOOOO OOOOOOOOOOOOO  O OO",
                                 "OOOOOOOOOOOOOO OOOOOOOOOOO OO OO",
                                 "OOOOOOO OOOOOOOOOOOOOO OO OOOOOO",
                                 "OOOOOO OOO O OOOOOO OOOOOOOOOOO ",
                                 "O OO OOO   OO OOOOOOOOO OOOOOOO ",
                                 "O OOOOO OOOOOOOOOO OO OOO OOO O ",
                                 "O OO O O OOOOOOO O O  OOO  OOOOO",
                                 "OOO OOOOOO OOOOOOOOO OO   OOOOOO",
                                 "OO O OOOOOO  OO O  O OO OOOOOOOO",
                                 "O OO  OOOO   OO   O   O  O OOO  ",
                                 "O OOOO  OO OO  OOOOO OO  OOOOOX ",
                                 "OOOOOO  OO  OOOOOO O O OOO OO OO",
                                 "O     O OOOOO O    OOO  O O O OO",
                                 "OOO  OOOOO o  O O  OO    OOO OX " };
#endif
