// ---------------------------------------------------------------------------------------------
// --------------- WARNING: this code is generated by an automatic code generator --------------
// ---------------------------------------------------------------------------------------------
// -------------- WARNING: any modifications made to this code will be overwritten -------------
// ---------------------------------------------------------------------------------------------

#ifndef US_HYDRODYN_CLUSTER_BEST_H
#define US_HYDRODYN_CLUSTER_BEST_H

#include "qcheckbox.h"
#include "qfontmetrics.h"
#include "qlabel.h"
#include "qlayout.h"
#include "qlineedit.h"
#include "qstring.h"
#include "us_hydrodyn_cluster.h"
//Added by qt3to4:
#include <QCloseEvent>
#include "qfile.h"
#include "qfiledialog.h"
#include "qmessagebox.h"
#include "qpushbutton.h"
#include "qregexp.h"
#include "us_hydrodyn.h"
#include "us_json.h"
#include "us_mqt.h"

using namespace std;

class US_EXTERN US_Hydrodyn_Cluster_Best : public QDialog {
      Q_OBJECT

   public:
      US_Hydrodyn_Cluster_Best(
         void *us_hydrodyn, map<QString, QString> *parameters, QWidget *p = 0, const char *name = 0);

      ~US_Hydrodyn_Cluster_Best();

   private:
      US_Config *USglobal;

      QLabel *lbl_title;
      QLabel *lbl_credits_1;
      QLabel *lbl_credits_2;
      QLabel *lbl_bestmsrprober;
      QLineEdit *le_bestmsrprober;
      QLabel *lbl_bestmsrfinenessangle;
      QLineEdit *le_bestmsrfinenessangle;
      QLabel *lbl_bestmsrmaxtriangles;
      QLineEdit *le_bestmsrmaxtriangles;
      QCheckBox *cb_bestrcoalautominmax;
      QLabel *lbl_bestrcoalnmin;
      QLineEdit *le_bestrcoalnmin;
      QLabel *lbl_bestrcoalnmax;
      QLineEdit *le_bestrcoalnmax;
      QLabel *lbl_bestrcoaln;
      QLineEdit *le_bestrcoaln;
      QLabel *lbl_bestbestmw;
      QLineEdit *le_bestbestmw;
      QLabel *lbl_bestexpand;
      QLineEdit *le_bestexpand;
      QCheckBox *cb_bestbestvc;
      QLabel *lbl_opt_label;
#if defined(WIN32) && QT_VERSION < 0x040000
#pragma warning(disable : 4251)
#endif
      vector<QWidget *> widgets_opt_label;
#if defined(WIN32) && QT_VERSION < 0x040000
#pragma warning(default : 4251)
#endif
      void hide_widgets(vector<QWidget *>, bool do_hide = true, bool do_resize = true);
      QLabel *lbl_bestmsrcoalescer;
      QLineEdit *le_bestmsrcoalescer;
      QCheckBox *cb_bestmsrusesomoradii;
      QLabel *lbl_bestmsrradiifile;
      QLineEdit *le_bestmsrradiifile;
      QLabel *lbl_bestmsrpatternfile;
      QLineEdit *le_bestmsrpatternfile;
      QPushButton *pb_save;
      QPushButton *pb_load;

      QPushButton *pb_help;
      QPushButton *pb_close;
      void *us_hydrodyn;
      map<QString, QString> *parameters;
      void update_fields();


      void setupGUI();

   private slots:

      void update_bestmsrprober(const QString &);
      void update_bestmsrfinenessangle(const QString &);
      void update_bestmsrmaxtriangles(const QString &);
      void set_bestrcoalautominmax();
      void update_bestrcoalnmin(const QString &);
      void update_bestrcoalnmax(const QString &);
      void update_bestrcoaln(const QString &);
      void update_bestbestmw(const QString &);
      void update_bestexpand(const QString &);
      void set_bestbestvc();
      void hide_opt_label();
      void update_bestmsrcoalescer(const QString &);
      void set_bestmsrusesomoradii();
      void update_bestmsrradiifile(const QString &);
      void update_bestmsrpatternfile(const QString &);
      void save();
      void load();

      void help();
      void cancel();

   protected slots:

      void closeEvent(QCloseEvent *);
};

#endif
