#ifndef US_LIMSCONV_H
#define US_LIMSCONV_H

const QString limsold[57] = {"uslims-amylin",
                             "uslims_anglia",
                             "uslims-bakh",
                             "uslims_baxter_at",
                             "uslims_bristol",
                             "uslims-burnet",
                             "cauma",
                             "uslims-charlesu",
                             "colostate",
                             "US-duesseldorf",
                             "uslims_embl",
                             "uslims-epfl",
                             "uslims-fmp",
                             "uslims-fsu",
                             "uslims_gilead",
                             "uslims_ibs",
                             "uslims-igbmc",
                             "uslims_lund",
                             "uslims_mainz",
                             "uslims-marshall",
                             "uslims-mcgill",
                             "uslims-mdacc",
                             "uslims_mit",
                             "uslims-mpig",
                             "uslims-ncmh",
                             "uslims-nhlbi",
                             "uslims_nrel",
                             "uslims-nwu",
                             "uslims-osaka",
                             "uslims-osu",
                             "uslims-pasteur",
                             "uslims_regensburg",
                             "uslims-rice",
                             "uslims-sbu",
                             "uslims-shriners",
                             "uslims_sinai",
                             "uslims-sinica",
                             "uslims-siuc",
                             "uslims-suny",
                             "uslims-tamu-hsc",
                             "uslims-tum",
                             "uslims-uglasgow",
                             "uslims-uic",
                             "uslims-uindiana",
                             "uslims-uky",
                             "uslims-um",
                             "uslims-umassmed",
                             "uslims-umc",
                             "uslims-umich",
                             "uslims-unimelb",
                             "uslims-utaustin",
                             "uslims-utoronto",
                             "uslims-utrecht",
                             "uslims-uvic",
                             "uslims-uwashington",
                             "uslims_uwashington_catalano",
                             "uslims-uwashington-klevit"};

const QString limsnew[57] = {
    "uslims2_amylin",      "uslims2_anglia",     "uslims2_bakh",
    "uslims2_baxter_at",   "uslims2_bristol",    "uslims2_burnet",
    "uslims2_cauma",       "uslims2_charlesu",   "uslims2_colostate",
    "uslims2_duesseldorf", "uslims2_embl",       "uslims2_epfl",
    "uslims2_fmp",         "uslims2_fsu",        "uslims2_gilead",
    "uslims2_ibs",         "uslims2_igbmc",      "uslims2_lund",
    "uslims2_mainz",       "uslims2_marshall",   "uslims2_mcgill",
    "uslims2_mdacc",       "uslims2_mit",        "uslims2_mpig",
    "uslims2_ncmh",        "uslims2_nhlbi",      "uslims2_nrel",
    "uslims2_nwu",         "uslims2_osaka",      "uslims2_osu",
    "uslims2_pasteur",     "uslims2_regensburg", "uslims2_rice",
    "uslims2_sbu",         "uslims2_shriners",   "uslims2_sinai",
    "uslims2_sinica",      "uslims2_siuc",       "uslims2_suny",
    "uslims2_tamu_hsc",    "uslims2_tum",        "uslims2_uglasgow",
    "uslims2_uic",         "uslims2_uindiana",   "uslims2_uky",
    "uslims2_um",          "uslims2_umassmed",   "uslims2_umc",
    "uslims2_umich",       "uslims2_unimelb",    "uslims2_utaustin",
    "uslims2_utoronto",    "uslims2_utrecht",    "uslims2_uvic",
    "uslims2_uwashington", "uslims2_uwcatalano", "uslims2_uwklevit"};

#endif
