#ifndef US_UNICODE_H
#define US_UNICODE_H

#define UNICODE_ANGSTROM u8"\u212B"
#define UNICODE_ANGSTROM_QS QString( "%1" ).arg( UNICODE_ANGSTROM )
#define UNICODE_PLUSMINUS u8"\u00B1"
#define UNICODE_PLUSMINUS_QS QString( "%1" ).arg( UNICODE_PLUSMINUS )
#define UNICODE_ALPHA u8"\u03B1"
#define UNICODE_ALPHA_QS QString( "%1" ).arg( UNICODE_ALPHA )
#define UNICODE_LAMBDA u8"\u03BB"
#define UNICODE_LAMBDA_QS QString( "%1" ).arg( UNICODE_LAMBDA )
#define UNICODE_SUPER_2 u8"\u00B2"
#define UNICODE_SUPER_2_QS QString( "%1" ).arg( UNICODE_SUPER_2 )
#define UNICODE_SUPER_3 u8"\u00B3"
#define UNICODE_SUPER_3_QS QString( "%1" ).arg( UNICODE_SUPER_3 )
#define UNICODE_SUPER_MINUS u8"\u207B"
#define UNICODE_SUPER_MINUS_QS QString( "%1" ).arg( UNICODE_SUPER_MINUS )

#endif 
