# =============================================================================
# somo_lib_sources.cmake  —  authoritative libus_somo source/header lists
# =============================================================================
# EXTRACTED from libus_somo.pro (SOURCES/HEADERS). Do NOT hand-glob src/*.cpp:
# several TUs under src/ are app-specific or otherwise excluded from the lib.
# Regenerate from the .pro if it changes; paths are relative to this dir
# (us_somo/develop) and prefixed with ${SOMO_ROOT}/ by the caller.
#
# Note: include/us_revision.h (a generated header, listed under SOURCES in the
# .pro) is intentionally omitted here — it is produced by the us_somo_revision
# target, not compiled. src/us_saxs_util_cuda.cpp IS included (lib member; the
# CUDA *define/toolchain* is gated separately by SOMO_ENABLE_CUDA).
# =============================================================================

set(SOMO_LIB_SOURCES
    src/us_admin.cpp
    src/us_arch.cpp
    src/us_average.cpp
    src/us_band_broaden.cpp
    src/us_container.cpp
    src/us_container_grpy.cpp
    src/us_cmdline_app.cpp
    src/us_config.cpp
    src/us_config_gui.cpp
    src/us_csv.cpp
    src/us_dirhist.cpp
    src/us_editor.cpp
    src/us_eigen.cpp
    src/us_encryption.cpp
    src/us_ffd.cpp
    src/us_file_util.cpp
    src/us_fractal_dimension.cpp
    src/us_font.cpp
    src/us_global.cpp
    src/us_help.cpp
    src/us_gzip.cpp
    src/us_hydrodyn.cpp
    src/us_hydrodyn_addatom.cpp
    src/us_hydrodyn_addhybrid.cpp
    src/us_hydrodyn_addresidue.cpp
    src/us_hydrodyn_addsaxs.cpp
    src/us_hydrodyn_advanced_config.cpp
    src/us_hydrodyn_anaflex_core.cpp
    src/us_hydrodyn_anaflex_options.cpp
    src/us_hydrodyn_asa.cpp
    src/us_hydrodyn_asab1.cpp
    src/us_hydrodyn_batch.cpp
    src/us_hydrodyn_batch_movie_opts.cpp
    src/us_hydrodyn_bead_output.cpp
    src/us_hydrodyn_beads.cpp
    src/us_hydrodyn_beads_load.cpp
    src/us_hydrodyn_best.cpp
    src/us_hydrodyn_bd.cpp
    src/us_hydrodyn_bd_core.cpp
    src/us_hydrodyn_bd_options.cpp
    src/us_hydrodyn_bd_load_results_opts.cpp
    src/us_hydrodyn_cluster.cpp
    src/us_hydrodyn_cluster_advanced.cpp
    src/us_hydrodyn_cluster_additional.cpp
    src/us_hydrodyn_cluster_best.cpp
    src/us_hydrodyn_cluster_bfnb.cpp
    src/us_hydrodyn_cluster_bfnb_nsa.cpp
    src/us_hydrodyn_cluster_config.cpp
    src/us_hydrodyn_cluster_config_server.cpp
    src/us_hydrodyn_cluster_dmd.cpp
    src/us_hydrodyn_cluster_dammin.cpp
    src/us_hydrodyn_cluster_oned.cpp
    src/us_hydrodyn_cluster_results.cpp
    src/us_hydrodyn_cluster_submit.cpp
    src/us_hydrodyn_cluster_status.cpp
    src/us_hydrodyn_comparative.cpp
    src/us_hydrodyn_core.cpp
    src/us_hydrodyn_csv_viewer.cpp
    src/us_hydrodyn_dammin_opts.cpp
    src/us_hydrodyn_dad.cpp
    src/us_hydrodyn_dad_baseline_best.cpp
    src/us_hydrodyn_dad_conc_csv_frames.cpp
    src/us_hydrodyn_dad_gui.cpp
    src/us_hydrodyn_dad_stack.cpp
    src/us_hydrodyn_dad_modes.cpp
    src/us_hydrodyn_dad_modes_bb.cpp
    src/us_hydrodyn_dad_modes_baseline2.cpp
    src/us_hydrodyn_dad_modes_guinier.cpp
    src/us_hydrodyn_dad_modes_powerfit.cpp
    src/us_hydrodyn_dad_modes_wheel.cpp
    src/us_hydrodyn_dad_makeiq.cpp
    src/us_hydrodyn_dad_plots.cpp
    src/us_hydrodyn_dad_ciq.cpp
    src/us_hydrodyn_dad_cistarq.cpp
    src/us_hydrodyn_dad_dctr.cpp
    src/us_hydrodyn_dad_gg.cpp
    src/us_hydrodyn_dad_p3d.cpp
    src/us_hydrodyn_dad_parameters.cpp
    src/us_hydrodyn_dad_util.cpp
    src/us_hydrodyn_dad_movie.cpp
    src/us_hydrodyn_dad_conc.cpp
    src/us_hydrodyn_dad_conc_load.cpp
    src/us_hydrodyn_dad_fit.cpp
    src/us_hydrodyn_dad_fit_global.cpp
    src/us_hydrodyn_dad_fit_gsm.cpp
    src/us_hydrodyn_dad_fit_ga.cpp
    src/us_hydrodyn_dad_gauss_mode.cpp
    src/us_hydrodyn_dad_nth.cpp
    src/us_hydrodyn_dad_options.cpp
    src/us_hydrodyn_dad_simulate.cpp
    src/us_hydrodyn_dad_svd.cpp
    src/us_hydrodyn_dad_scale_trend.cpp
    src/us_hydrodyn_dmd_core.cpp
    src/us_hydrodyn_dmd_options.cpp
    src/us_hydrodyn_file.cpp
    src/us_hydrodyn_file2.cpp
    src/us_hydrodyn_fractal_dimension.cpp
    src/us_hydrodyn_fractal_dimension_options.cpp
    src/us_hydrodyn_grid.cpp
    src/us_hydrodyn_grid_atob.cpp
    src/us_hydrodyn_grpy.cpp
    src/us_hydrodyn_hydrate.cpp
    src/us_hydrodyn_hydrate_align.cpp
    src/us_hydrodyn_hydro.cpp
    src/us_hydrodyn_hydro_zeno.cpp
    src/us_hydrodyn_info.cpp
    src/us_hydrodyn_load.cpp
    src/us_hydrodyn_mals.cpp
    src/us_hydrodyn_mals_baseline_best.cpp
    src/us_hydrodyn_mals_conc_csv_frames.cpp
    src/us_hydrodyn_mals_gui.cpp
    src/us_hydrodyn_mals_stack.cpp
    src/us_hydrodyn_mals_modes.cpp
    src/us_hydrodyn_mals_modes_guinier.cpp
    src/us_hydrodyn_mals_modes_bb.cpp
    src/us_hydrodyn_mals_modes_wheel.cpp
    src/us_hydrodyn_mals_makeiq.cpp
    src/us_hydrodyn_mals_plots.cpp
    src/us_hydrodyn_mals_ciq.cpp
    src/us_hydrodyn_mals_cistarq.cpp
    src/us_hydrodyn_mals_dctr.cpp
    src/us_hydrodyn_mals_gg.cpp
    src/us_hydrodyn_mals_p3d.cpp
    src/us_hydrodyn_mals_parameters.cpp
    src/us_hydrodyn_mals_util.cpp
    src/us_hydrodyn_mals_movie.cpp
    src/us_hydrodyn_mals_conc.cpp
    src/us_hydrodyn_mals_conc_load.cpp
    src/us_hydrodyn_mals_fit.cpp
    src/us_hydrodyn_mals_fit_global.cpp
    src/us_hydrodyn_mals_fit_gsm.cpp
    src/us_hydrodyn_mals_fit_ga.cpp
    src/us_hydrodyn_mals_gauss_mode.cpp
    src/us_hydrodyn_mals_nth.cpp
    src/us_hydrodyn_mals_options.cpp
    src/us_hydrodyn_mals_simulate.cpp
    src/us_hydrodyn_mals_svd.cpp
    src/us_hydrodyn_mals_scale_trend.cpp
    src/us_hydrodyn_mals_saxs.cpp
    src/us_hydrodyn_mals_saxs_baseline_best.cpp
    src/us_hydrodyn_mals_saxs_conc_csv_frames.cpp
    src/us_hydrodyn_mals_saxs_gui.cpp
    src/us_hydrodyn_mals_saxs_stack.cpp
    src/us_hydrodyn_mals_saxs_modes.cpp
    src/us_hydrodyn_mals_saxs_modes_guinier.cpp
    src/us_hydrodyn_mals_saxs_modes_bb.cpp
    src/us_hydrodyn_mals_saxs_modes_scroll.cpp
    src/us_hydrodyn_mals_saxs_modes_scale.cpp
    src/us_hydrodyn_mals_saxs_modes_wheel.cpp
    src/us_hydrodyn_mals_saxs_makeiq.cpp
    src/us_hydrodyn_mals_saxs_plots.cpp
    src/us_hydrodyn_mals_saxs_ciq.cpp
    src/us_hydrodyn_mals_saxs_cistarq.cpp
    src/us_hydrodyn_mals_saxs_dctr.cpp
    src/us_hydrodyn_mals_saxs_gg.cpp
    src/us_hydrodyn_mals_saxs_p3d.cpp
    src/us_hydrodyn_mals_saxs_parameters.cpp
    src/us_hydrodyn_mals_saxs_util.cpp
    src/us_hydrodyn_mals_saxs_movie.cpp
    src/us_hydrodyn_mals_saxs_conc.cpp
    src/us_hydrodyn_mals_saxs_conc_load.cpp
    src/us_hydrodyn_mals_saxs_fit.cpp
    src/us_hydrodyn_mals_saxs_fit_global.cpp
    src/us_hydrodyn_mals_saxs_fit_gsm.cpp
    src/us_hydrodyn_mals_saxs_fit_ga.cpp
    src/us_hydrodyn_mals_saxs_gauss_mode.cpp
    src/us_hydrodyn_mals_saxs_nth.cpp
    src/us_hydrodyn_mals_saxs_options.cpp
    src/us_hydrodyn_mals_saxs_simulate.cpp
    src/us_hydrodyn_mals_saxs_svd.cpp
    src/us_hydrodyn_mals_saxs_scale_trend.cpp
    src/us_hydrodyn_misc.cpp
    src/us_hydrodyn_other.cpp
    src/us_hydrodyn_overlap.cpp
    src/us_hydrodyn_overlap_reduction.cpp
    src/us_hydrodyn_pat.cpp
    src/us_hydrodyn_pdb_parsing.cpp
    src/us_hydrodyn_pdb_tool.cpp
    src/us_hydrodyn_pdb_tool_merge.cpp
    src/us_hydrodyn_pdb_tool_renum.cpp
    src/us_hydrodyn_pdb_tool_selres.cpp
    src/us_hydrodyn_pdb_tool_sort.cpp
    src/us_hydrodyn_pdb_tool_util.cpp
    src/us_hydrodyn_pdb_visualization.cpp
    src/us_hydrodyn_results.cpp
    src/us_hydrodyn_sas_options_saxs.cpp
    src/us_hydrodyn_sas_options_sans.cpp
    src/us_hydrodyn_sas_options_curve.cpp
    src/us_hydrodyn_sas_options_bead_model.cpp
    src/us_hydrodyn_sas_options_hydration.cpp
    src/us_hydrodyn_sas_options_guinier.cpp
    src/us_hydrodyn_sas_options_xsr.cpp
    src/us_hydrodyn_sas_options_misc.cpp
    src/us_hydrodyn_sas_options_experimental.cpp
    src/us_hydrodyn_save.cpp
    src/us_hydrodyn_saxs.cpp
    src/us_hydrodyn_saxs_conc.cpp
    src/us_hydrodyn_saxs_cormap.cpp
    src/us_hydrodyn_saxs_external.cpp
    src/us_hydrodyn_saxs_guinier.cpp
    src/us_hydrodyn_saxs_fits.cpp
    src/us_hydrodyn_saxs_ift.cpp
    src/us_hydrodyn_saxs_iqq.cpp
    src/us_hydrodyn_saxs_iqq_bead_model.cpp
    src/us_hydrodyn_saxs_iqq_load_csv.cpp
    src/us_hydrodyn_saxs_iqq_residuals.cpp
    src/us_hydrodyn_saxs_iqq_sh.cpp
    src/us_hydrodyn_saxs_load_csv.cpp
    src/us_hydrodyn_saxs_loads.cpp
    src/us_hydrodyn_saxs_legend.cpp
    src/us_hydrodyn_saxs_mw.cpp
    src/us_hydrodyn_saxs_options.cpp
    src/us_hydrodyn_saxs_plots.cpp
    src/us_hydrodyn_saxs_pr.cpp
    src/us_hydrodyn_saxs_residuals.cpp
    src/us_hydrodyn_saxs_screen.cpp
    src/us_hydrodyn_saxs_search.cpp
    src/us_hydrodyn_saxs_buffer.cpp
    src/us_hydrodyn_saxs_buffer_gui.cpp
    src/us_hydrodyn_saxs_buffer_fit.cpp
    src/us_hydrodyn_saxs_buffer_conc.cpp
    src/us_hydrodyn_saxs_buffer_conc_load.cpp
    src/us_hydrodyn_saxs_buffer_nth.cpp
    src/us_hydrodyn_saxs_hplc.cpp
    src/us_hydrodyn_saxs_hplc_baseline_best.cpp
    src/us_hydrodyn_saxs_hplc_conc_csv_frames.cpp
    src/us_hydrodyn_saxs_hplc_gui.cpp
    src/us_hydrodyn_saxs_hplc_stack.cpp
    src/us_hydrodyn_saxs_hplc_modes.cpp
    src/us_hydrodyn_saxs_hplc_modes_bb.cpp
    src/us_hydrodyn_saxs_hplc_modes_broaden.cpp
    src/us_hydrodyn_saxs_hplc_modes_wheel.cpp
    src/us_hydrodyn_saxs_hplc_makeiq.cpp
    src/us_hydrodyn_saxs_hplc_parameters.cpp
    src/us_hydrodyn_saxs_hplc_plots.cpp
    src/us_hydrodyn_saxs_hplc_ciq.cpp
    src/us_hydrodyn_saxs_hplc_dctr.cpp
    src/us_hydrodyn_saxs_hplc_gg.cpp
    src/us_hydrodyn_saxs_hplc_p3d.cpp
    src/us_hydrodyn_saxs_hplc_util.cpp
    src/us_hydrodyn_saxs_hplc_movie.cpp
    src/us_hydrodyn_saxs_hplc_conc.cpp
    src/us_hydrodyn_saxs_hplc_conc_load.cpp
    src/us_hydrodyn_saxs_hplc_fit.cpp
    src/us_hydrodyn_saxs_hplc_fit_global.cpp
    src/us_hydrodyn_saxs_hplc_fit_gsm.cpp
    src/us_hydrodyn_saxs_hplc_fit_ga.cpp
    src/us_hydrodyn_saxs_hplc_gauss_mode.cpp
    src/us_hydrodyn_saxs_hplc_nth.cpp
    src/us_hydrodyn_saxs_hplc_options.cpp
    src/us_hydrodyn_saxs_hplc_simulate.cpp
    src/us_hydrodyn_saxs_hplc_svd.cpp
    src/us_hydrodyn_saxs_hplc_scale_trend.cpp
    src/us_hydrodyn_saxs_1d.cpp
    src/us_hydrodyn_saxs_2d.cpp
    src/us_hydrodyn_script.cpp
    src/us_hydrodyn_settings.cpp
    src/us_hydrodyn_supc.cpp
    src/us_hydrodyn_util.cpp
    src/us_hydrodyn_vdw_overlap.cpp
    src/us_hydrodyn_xsr.cpp
    src/us_hydrodyn_write.cpp
    src/us_hydrodyn_zeno.cpp
    src/us_json.cpp
    src/us_mqt.cpp
    src/us_license.cpp
    src/us_lm.cpp
    src/us_lud.cpp
    src/us_math.cpp
    src/us_matrix.cpp
    src/us_pdb_util.cpp
    src/us_pm.cpp
    src/us_pm_best.cpp
    src/us_pm_best_sphere.cpp
    src/us_pm_best_cylinder.cpp
    src/us_pm_best_spheroid.cpp
    src/us_pm_best_ellipsoid.cpp
    src/us_pm_best_torus.cpp
    src/us_pm_best_torus_segment.cpp
    src/us_pm_fitness.cpp
    src/us_pm_ga.cpp
    src/us_pm_objects.cpp
    src/us_pm_test.cpp
    src/us_plot_zoom.cpp
    src/us_register.cpp
    src/us_saxs_gp.cpp
    src/us_saxs_util.cpp
    src/us_saxs_util_asab1.cpp
    src/us_saxs_util_a2sb.cpp
    src/us_saxs_util_best.cpp
    src/us_saxs_util_c2check.cpp
    src/us_saxs_util_crysol.cpp
    src/us_saxs_util_cuda.cpp
    src/us_saxs_util_dammin.cpp
    src/us_saxs_util_dmd.cpp
    src/us_saxs_util_extern.cpp
    src/us_saxs_util_guinier.cpp
    src/us_saxs_util_gui_only.cpp
    src/us_saxs_util_hydrate.cpp
    src/us_saxs_util_hydrate_align.cpp
    src/us_saxs_util_ift.cpp
    src/us_saxs_util_iqq.cpp
    src/us_saxs_util_iqq_1d.cpp
    src/us_saxs_util_iqq_pdb.cpp
    src/us_saxs_util_iqq_bead_model.cpp
    src/us_saxs_util_loads.cpp
    src/us_saxs_util_nsa.cpp
    src/us_saxs_util_nsa_ga.cpp
    src/us_saxs_util_nsa_gsm.cpp
    src/us_saxs_util_nsa_sga.cpp
    src/us_saxs_util_pat.cpp
    src/us_saxs_util_pm.cpp
    src/us_saxs_util_sgp.cpp
    src/us_saxs_util_sgp_phys.cpp
    src/us_saxs_util_ssbond.cpp
    src/us_saxs_util_static.cpp
    src/us_sh.cpp
    src/us_surfracer.cpp
    src/us_svd.cpp
    src/us_efa.cpp
    src/us_tar.cpp
    src/us_timer.cpp
    src/us_util.cpp
    src/us_vector.cpp
    src/us_vvv.cpp
    src/us_write_config.cpp
    src/us_zeno_cxx.cpp
    src/us_zeno_cxx_nf.cpp
    src/qwt/scrollbar.cpp
    src/qwt/scrollzoomer.cpp
    src/us_gui_settings.cpp
    src/us_hydrodyn_saxs_guinier_frames.cpp
    src/us_plot_util.cpp
    src/us3i_color.cpp
    src/us3i_editor.cpp
    src/us3i_editor_gui.cpp
    src/us3i_gui_settings.cpp
    src/us3i_settings.cpp
    src/us3i_widgets.cpp
    src/us3i_widgets_dialog.cpp
    src/us3i_images.cpp
    src/us3i_global.cpp
    src/us3i_gui_util.cpp
    src/us3i_util.cpp
    src/us3i_gzip.cpp
    src/us3i_plot.cpp
    shd_mpi/shs_use.cpp
)

set(SOMO_LIB_HEADERS
    include/us.h
    include/us_admin.h
    include/us_arch.h
    include/us_average.h
    include/us_band_broaden.h
    include/us_container.h
    include/us_container_grpy.h
    include/us_cmdline_app.h
    include/us_config_gui.h
    include/us_csv.h
    include/us_dirhist.h
    include/us_editor.h
    include/us_extern.h
    include/us_ffd.h
    include/us_file_util.h
    include/us_font.h
    include/us_gzip.h
    include/us_hydrodyn.h
    include/us_hydrodyn_addatom.h
    include/us_hydrodyn_addhybrid.h
    include/us_hydrodyn_addresidue.h
    include/us_hydrodyn_addsaxs.h
    include/us_hydrodyn_advanced_config.h
    include/us_hydrodyn_anaflex_options.h
    include/us_hydrodyn_asa.h
    include/us_hydrodyn_asab1.h
    include/us_hydrodyn_batch.h
    include/us_hydrodyn_batch_movie_opts.h
    include/us_hydrodyn_bd.h
    include/us_hydrodyn_bd_options.h
    include/us_hydrodyn_bd_load_results_opts.h
    include/us_hydrodyn_bead_output.h
    include/us_hydrodyn_best.h
    include/us_hydrodyn_cluster.h
    include/us_hydrodyn_cluster_additional.h
    include/us_hydrodyn_cluster_advanced.h
    include/us_hydrodyn_cluster_bfnb.h
    include/us_hydrodyn_cluster_best.h
    include/us_hydrodyn_cluster_bfnb_nsa.h
    include/us_hydrodyn_cluster_config.h
    include/us_hydrodyn_cluster_config_server.h
    include/us_hydrodyn_cluster_dammin.h
    include/us_hydrodyn_cluster_dmd.h
    include/us_hydrodyn_cluster_oned.h
    include/us_hydrodyn_cluster_results.h
    include/us_hydrodyn_cluster_submit.h
    include/us_hydrodyn_cluster_status.h
    include/us_hydrodyn_comparative.h
    include/us_hydrodyn_csv_viewer.h
    include/us_hydrodyn_dammin_opts.h
    include/us_hydrodyn_dad.h
    include/us_hydrodyn_dad_ciq.h
    include/us_hydrodyn_dad_cistarq.h
    include/us_hydrodyn_dad_conc_csv_frames.h
    include/us_hydrodyn_dad_dctr.h
    include/us_hydrodyn_dad_p3d.h
    include/us_hydrodyn_dad_parameters.h
    include/us_hydrodyn_dad_conc.h
    include/us_hydrodyn_dad_conc_load.h
    include/us_hydrodyn_dad_fit.h
    include/us_hydrodyn_dad_fit_global.h
    include/us_hydrodyn_dad_gauss_mode.h
    include/us_hydrodyn_dad_movie.h
    include/us_hydrodyn_dad_nth.h
    include/us_hydrodyn_dad_options.h
    include/us_hydrodyn_dad_scale_trend.h
    include/us_hydrodyn_dad_svd.h
    include/us_hydrodyn_dad_baseline_best.h
    include/us_hydrodyn_dad_simulate.h
    include/us_hydrodyn_dmd_options.h
    include/us_hydrodyn_file.h
    include/us_hydrodyn_file2.h
    include/us_fractal_dimension.h
    include/us_hydrodyn_fractal_dimension_options.h
    include/us_hydrodyn_grid.h
    include/us_hydrodyn_grid_atob.h
    include/us_hydrodyn_hydro.h
    include/us_hydrodyn_hydro_zeno.h
    include/us_hydrodyn_mals.h
    include/us_hydrodyn_mals_ciq.h
    include/us_hydrodyn_mals_cistarq.h
    include/us_hydrodyn_mals_conc_csv_frames.h
    include/us_hydrodyn_mals_dctr.h
    include/us_hydrodyn_mals_p3d.h
    include/us_hydrodyn_mals_parameters.h
    include/us_hydrodyn_mals_conc.h
    include/us_hydrodyn_mals_conc_load.h
    include/us_hydrodyn_mals_fit.h
    include/us_hydrodyn_mals_fit_global.h
    include/us_hydrodyn_mals_gauss_mode.h
    include/us_hydrodyn_mals_movie.h
    include/us_hydrodyn_mals_nth.h
    include/us_hydrodyn_mals_options.h
    include/us_hydrodyn_mals_scale_trend.h
    include/us_hydrodyn_mals_svd.h
    include/us_hydrodyn_mals_baseline_best.h
    include/us_hydrodyn_mals_simulate.h
    include/us_hydrodyn_mals_saxs.h
    include/us_hydrodyn_mals_saxs_ciq.h
    include/us_hydrodyn_mals_saxs_cistarq.h
    include/us_hydrodyn_mals_saxs_conc_csv_frames.h
    include/us_hydrodyn_mals_saxs_dctr.h
    include/us_hydrodyn_mals_saxs_p3d.h
    include/us_hydrodyn_mals_saxs_parameters.h
    include/us_hydrodyn_mals_saxs_conc.h
    include/us_hydrodyn_mals_saxs_conc_load.h
    include/us_hydrodyn_mals_saxs_fit.h
    include/us_hydrodyn_mals_saxs_fit_global.h
    include/us_hydrodyn_mals_saxs_gauss_mode.h
    include/us_hydrodyn_mals_saxs_movie.h
    include/us_hydrodyn_mals_saxs_nth.h
    include/us_hydrodyn_mals_saxs_options.h
    include/us_hydrodyn_mals_saxs_scale_trend.h
    include/us_hydrodyn_mals_saxs_svd.h
    include/us_hydrodyn_mals_saxs_baseline_best.h
    include/us_hydrodyn_mals_saxs_simulate.h
    include/us_hydrodyn_misc.h
    include/us_hydrodyn_overlap.h
    include/us_hydrodyn_overlap_reduction.h
    include/us_hydrodyn_pdbdefs.h
    include/us_hydrodyn_pat.h
    include/us_hydrodyn_pdb_parsing.h
    include/us_hydrodyn_pdb_tool.h
    include/us_hydrodyn_pdb_tool_merge.h
    include/us_hydrodyn_pdb_tool_renum.h
    include/us_hydrodyn_pdb_tool_selres.h
    include/us_hydrodyn_pdb_tool_sort.h
    include/us_hydrodyn_pdb_visualization.h
    include/us_hydrodyn_results.h
    include/us_hydrodyn_sas_options_saxs.h
    include/us_hydrodyn_sas_options_sans.h
    include/us_hydrodyn_sas_options_curve.h
    include/us_hydrodyn_sas_options_bead_model.h
    include/us_hydrodyn_sas_options_hydration.h
    include/us_hydrodyn_sas_options_guinier.h
    include/us_hydrodyn_sas_options_xsr.h
    include/us_hydrodyn_sas_options_misc.h
    include/us_hydrodyn_sas_options_experimental.h
    include/us_hydrodyn_save.h
    include/us_hydrodyn_saxs.h
    include/us_hydrodyn_saxs_conc.h
    include/us_hydrodyn_saxs_load_csv.h
    include/us_hydrodyn_saxs_mw.h
    include/us_hydrodyn_saxs_options.h
    include/us_hydrodyn_saxs_ift.h
    include/us_hydrodyn_saxs_iqq_load_csv.h
    include/us_hydrodyn_saxs_iqq_residuals.h
    include/us_hydrodyn_saxs_residuals.h
    include/us_hydrodyn_saxs_screen.h
    include/us_hydrodyn_saxs_search.h
    include/us_hydrodyn_saxs_buffer.h
    include/us_hydrodyn_saxs_buffer_conc.h
    include/us_hydrodyn_saxs_buffer_conc_load.h
    include/us_hydrodyn_saxs_buffer_nth.h
    include/us_hydrodyn_saxs_hplc.h
    include/us_hydrodyn_saxs_hplc_ciq.h
    include/us_hydrodyn_saxs_hplc_conc_csv_frames.h
    include/us_hydrodyn_saxs_hplc_dctr.h
    include/us_hydrodyn_saxs_hplc_p3d.h
    include/us_hydrodyn_saxs_hplc_conc.h
    include/us_hydrodyn_saxs_hplc_conc_load.h
    include/us_hydrodyn_saxs_hplc_fit.h
    include/us_hydrodyn_saxs_hplc_fit_global.h
    include/us_hydrodyn_saxs_hplc_gauss_mode.h
    include/us_hydrodyn_saxs_hplc_movie.h
    include/us_hydrodyn_saxs_hplc_nth.h
    include/us_hydrodyn_saxs_hplc_options.h
    include/us_hydrodyn_saxs_hplc_parameters.h
    include/us_hydrodyn_saxs_hplc_scale_trend.h
    include/us_hydrodyn_saxs_hplc_svd.h
    include/us_hydrodyn_saxs_hplc_baseline_best.h
    include/us_hydrodyn_saxs_hplc_simulate.h
    include/us_hydrodyn_saxs_1d.h
    include/us_hydrodyn_saxs_2d.h
    include/us_hydrodyn_supc.h
    include/us_hydrodyn_vdw_overlap.h
    include/us_hydrodyn_xsr.h
    include/us_hydrodyn_zeno.h
    include/us_fable.h
    include/us_json.h
    include/us_mqt.h
    include/us_license.h
    include/us_lm.h
    include/us_lud.h
    include/us_math.h
    include/us_matrix.h
    include/us_pdb_util.h
    include/us_pm.h
    include/us_plot_zoom.h
    include/us_register.h
    include/us_revision.h
    include/us_saxs_gp.h
    include/us_saxs_util.h
    include/us_saxs_util_nsa.h
    include/us_sh.h
    include/us_surfracer.h
    include/us_svd.h
    include/us_efa.h
    include/us_eigen.h
    include/us_tar.h
    include/us_timer.h
    include/us_thread.h
    include/us_tnt_jama.h
    include/us_unicode.h
    include/us_util.h
    include/us_vector.h
    include/us_version.h
    include/us_vvv.h
    include/us_write_config.h
    include/us_zeno_cxx.h
    include/us_zeno_cxx_nf.h
    include/us3_extern.h
    include/us3_defines.h
    include/us_gui_settings.h
    include/qwt/scrollbar.h
    include/qwt/scrollzoomer.h
    include/us_hydrodyn_saxs_guinier_frames.h
    include/us_hydrodyn_saxs_cormap.h
    include/us_plot_util.h
    include/us3i_color.h
    include/us3i_extern.h
    include/us3i_editor.h
    include/us3i_editor_gui.h
    include/us3i_gui_settings.h
    include/us3i_settings.h
    include/us3i_widgets.h
    include/us3i_widgets_dialog.h
    include/us3i_images.h
    include/us3i_global.h
    include/us3i_gui_util.h
    include/us3i_util.h
    include/us3i_gzip.h
    include/us3i_plot.h
    include/us3i_pixmaps.h
    shd_mpi/shs_data.h
)
