#!/usr/bin/env python3
"""Derive a hybrid-type -> hydration (waters) lookup from somo.residue.

Mattia's step 3: "We could potentially build a table of atom hybridizations from our
somo.residue table linked to their hydration numbers. Based on this, for the new residue ...
proposed atomic hydration are shown, to be interactively modified."

This builds that table, and reports honestly where it is solid and where it is not.

WHAT THE DATA ACTUALLY IS
`somo.residue` stores hydration **per atom** (field 8 of each atom line). Summed per residue, it
reproduces the classical Kuntz per-residue numbers (Durchschlag 1986 Table 1, pH 6-8): 14 of the
20 amino acids agree within 0.5 water, and the two large misses -- Asp (1 vs 6) and Glu (1 vs
7.5) -- are exactly the residues SOMO stores PROTONATED, so they carry no charged-carboxylate
water. So the per-atom numbers are a **hand distribution of a per-residue Kuntz total**, not an
independently derived per-atom physical rule.

CONSEQUENCE, AND WHY THIS TABLE IS STILL THE RIGHT DELIVERABLE
Because it is a hand distribution, the same chemical group is sometimes hydrated in one entry and
not in another (ADP.O2' = 1 but A.O2' = 0; BMA.O2/O3/O6 = 1 but BMA.O4 = 0). A per-type lookup
therefore captures the dominant pattern with real exceptions -- which is exactly the right shape
for a *proposed* value the user then edits interactively. It is NOT a physical prediction, and
should not be presented to the user as one.

Two numbers are worth showing the user: the per-atom proposal (from this table) and the resulting
RESIDUE TOTAL, since the total is the quantity that actually has literature backing.

Usage:  python3 tools/hydration_table.py [--cpp]      (run from perceiver/)
"""
import sys
from collections import defaultdict, Counter

RESFILE = "../../etc/somo.residue.new"
UNANIMOUS, MAJORITY = 1.0, 0.75


def load(path):
    lines = open(path).read().splitlines()
    byhyb = defaultdict(list)
    i, seen = 0, set()
    while i < len(lines):
        i += 1
        if i >= len(lines):
            break
        h = lines[i].split()
        if len(h) < 7:
            continue
        i += 1
        try:
            nm, na, nb = h[0], int(h[4]), int(h[5])
        except (ValueError, IndexError):
            continue
        if nm not in seen:
            seen.add(nm)
            for j in range(i, min(i + na, len(lines))):
                p = lines[j].split("\t")
                if len(p) >= 8:
                    try:
                        w = float(p[7])
                    except ValueError:
                        continue
                    byhyb[p[1].strip()].append((w, nm, p[0].strip()))
        i += na + max(nb, 0)
    return byhyb


def main():
    byhyb = load(RESFILE)
    rows = []
    for hyb in sorted(byhyb):
        obs = byhyb[hyb]
        c = Counter(w for w, _, _ in obs)
        default, hits = c.most_common(1)[0]
        agree = hits / len(obs)
        conf = ("unanimous" if agree >= UNANIMOUS else
                "majority" if agree >= MAJORITY else "WEAK")
        rows.append((hyb, default, len(obs), agree, conf, c))

    print("%-9s %8s %5s %8s  %-10s %s" %
          ("hybrid", "default", "n", "agree", "confidence", "other values seen"))
    for hyb, d, n, a, conf, c in rows:
        others = ", ".join("%g x%d" % (v, k) for v, k in sorted(c.items()) if v != d)
        print("%-9s %8g %5d %7.0f%%  %-10s %s" % (hyb, d, n, 100 * a, conf, others))

    weak = [r for r in rows if r[4] == "WEAK"]
    maj = [r for r in rows if r[4] == "majority"]
    una = [r for r in rows if r[4] == "unanimous"]
    print("\n%d unanimous, %d majority, %d WEAK (of %d types)" %
          (len(una), len(maj), len(weak), len(rows)))
    if weak:
        print("WEAK types must be flagged for user review, never silently defaulted:")
        for hyb, d, n, a, _, c in weak:
            print("   %-8s default %g but only %.0f%% of %d observations  %s"
                  % (hyb, d, 100 * a, n, dict(c)))

    if "--cpp" in sys.argv:
        print("\n// generated by tools/hydration_table.py from somo.residue")
        print("// PROPOSED defaults only -- the user edits these interactively.")
        print("// .second = true where the value is well supported; false = flag for review.")
        print("static const std::map<std::string, std::pair<double,bool>> hydration_default = {")
        for hyb, d, n, a, conf, c in rows:
            print('    {"%s", {%g, %s}},   // n=%d agree=%.0f%%'
                  % (hyb, d, "true" if conf != "WEAK" else "false", n, 100 * a))
        print("};")
    return 0


if __name__ == "__main__":
    sys.exit(main())
