#!/bin/sh

#This is primarily for Windows 

for each in us*; do
  if [ -d $each ]; then
    cd $each
    echo $each
    #[ -f us*.pro ] && qmake us*.pro
    rm *.vcproj*
    rm Debug/*
    rm Release/*
    cd ..
  fi
done

#qmake libus.pro

#[ -e *.vcproj ] && sed -i -e 's/Release\\\\/..\\bin\\/' *.vcproj
#[ -e *.vcproj ] && sed -i -e 's/Debug\\\\/..\\bin\\/' *.vcproj

for each in us*; do
  if [ -d $each ]; then
    cd $each
    echo $each
    [ -f us*.pro ] && qmake us*.pro
    [ -e *.vcproj ] && sed -i -e 's/Release\\\\/..\\..\\bin\\/' *.vcproj
    [ -e *.vcproj ] && sed -i -e 's/Debug\\\\/..\\..\\bin\\/' *.vcproj
    cd ..
  fi
done


qmake us_all.pro
