#!/bin/sh


sed -i  's/debug/release/g' libus.pro
sed -i  's/debug/release/g' generic.pri


for each in us*; do
  if [ -d $each ]; then
    cd $each
    echo $each

#  This should not be necessary when the .pro files all use generic.pri
    for f in *.pro; do
        sed -i 's/debug/release/g' $f
    done

    qmake us*.pro
    cd ..
  fi
done
