#!/usr/bin/perl
$ultrascan = $ENV{'ULTRASCAN'};
$ultrascan = "/usr/local/ultrascan2" if !$ultrascan;
open(FH, "$ultrascan/etc/grid/tigre_sysstat");
flock(FH, 2) || print STDERR "$0: Warning can not flock $ultrascan/etc/grid/tigre_sysstat\n";
system("cat $ultrascan/etc/grid/tigre_sysstat");
close(FH);
