// ---------------------------------------------------------------------------------------------
// --------------- WARNING: this code is generated by an automatic code
// generator --------------
// ---------------------------------------------------------------------------------------------
// -------------- WARNING: any modifications made to this code will be
// overwritten -------------
// ---------------------------------------------------------------------------------------------

___cpp_header___ ___classname___::___classname______cpp_input_variables___
    : QFrame(p, name) {
  ___cpp_inputs___ USglobal = new US_Config();
  setPalette(QPalette(USglobal->global_colors.cg_frame,
                      USglobal->global_colors.cg_frame,
                      USglobal->global_colors.cg_frame));
  setCaption(tr(___title___));

  setupGUI();

  global_Xpos += 30;
  global_Ypos += 30;

  setGeometry(global_Xpos, global_Ypos, 0, 0);
}

___classname___::~___classname___() {}

void ___classname___::setupGUI() {
  int minHeight1 = 30;
  ___setup_gui___ pb_help = new QPushButton(tr("Help"), this);
  pb_help->setFont(QFont(USglobal->config_list.fontFamily,
                         USglobal->config_list.fontSize + 1));
  pb_help->setMinimumHeight(minHeight1);
  pb_help->setPalette(QPalette(USglobal->global_colors.cg_pushb,
                               USglobal->global_colors.cg_pushb_disabled,
                               USglobal->global_colors.cg_pushb_active));
  connect(pb_help, SIGNAL(clicked()), SLOT(help()));

  pb_close = new QPushButton(tr("Close"), this);
  pb_close->setFont(QFont(USglobal->config_list.fontFamily,
                          USglobal->config_list.fontSize + 1));
  pb_close->setMinimumHeight(minHeight1);
  pb_close->setPalette(QPalette(USglobal->global_colors.cg_pushb,
                                USglobal->global_colors.cg_pushb_disabled,
                                USglobal->global_colors.cg_pushb_active));
  connect(pb_close, SIGNAL(clicked()), SLOT(cancel()));

  QVBoxLayout *background = new QVBoxLayout(this);
  background->addSpacing(4);

  ___finalize_gui___

      QHBoxLayout *hbl_bottom = new QHBoxLayout(0);
  hbl_bottom->addSpacing(4);
  hbl_bottom->addWidget(pb_help);
  hbl_bottom->addSpacing(4);
  hbl_bottom->addWidget(pb_close);
  hbl_bottom->addSpacing(4);

  background->addLayout(hbl_bottom);
  background->addSpacing(4);
}

void ___classname___::cancel() { close(); }

void ___classname___::help() {
  US_Help *online_help;
  online_help = new US_Help(this);
  online_help->show_help("manual/___helpname___.html");
}

void ___classname___::closeEvent(QCloseEvent *e) {
  ___cpp_clean_parameters___ global_Xpos -= 30;
  global_Ypos -= 30;
  e->accept();
}
___cpp_functions___
