// ---------------------------------------------------------------------------------------------
// --------------- WARNING: this code is generated by an automatic code
// generator --------------
// ---------------------------------------------------------------------------------------------
// -------------- WARNING: any modifications made to this code will be
// overwritten -------------
// ---------------------------------------------------------------------------------------------

#include "../include/us_cmdline_app.h"
#include "../include/us_saxs_util.h"

bool US_Saxs_Util::___cmdline_run_application___ {
  errormsg = "";
  QStringList args;
  QStringList app_text;
  QStringList response;

  ___cmdline_interface_init___

      // check requireed parameters defined ?

      int argc = 0;
  // const char *argv0 = "us_saxs_util";
  // const char **argv = &argv0;
  char **argv = (char **)0;
  QApplication app(argc, argv, false);

  QString cla_error_msg;
  US_Cmdline_App cla(&app,
                     "",  // dir
                     args, app_text, response, &cla_error_msg, 240000);

  if (!cla_error_msg.isEmpty()) {
    errormsg = cla_error_msg;
    return false;
  }

  app.exec();

  if (!cla_error_msg.isEmpty()) {
    errormsg = "Error: ___cmdline_run_application___:" + cla_error_msg;
    return false;
  }
  ___cmdline_interface_post_processing___ return true;
}
